<?php

namespace slvler\mysqlconnectors\Config;

class Method extends Sql {

    public $connection;


    public function __construct($connection){
        parent::__construct($connection);
    }

   public function Select_ch($table,$data = array())
   {
       return parent::Select_ch($table,$data);
   }

    public function Select_all($table){
        return parent::Select_all($table);
    }

    public function Select_wh($table, $data = array(),$con = array(), $if = array())
    {
       return parent::Select_wh($table, $data, $con, $if); // TODO: Change the autogenerated stub
    }

    public function Insert($table, $data = array())
    {
        return parent::Insert($table, $data); // TODO: Change the autogenerated stub
    }

    public function Update($table, $id = array(), $data = array())
    {
       return parent::Update($table, $id, $data); // TODO: Change the autogenerated stub
    }
    public function Delete($table, $id = array())
    {
        return parent::Delete($table, $id); // TODO: Change the autogenerated stub
    }
}


?>